### ISSUE TITLE
小白求助

### ISSUE THREAD

**Issue by tzSmilence** [bojone/margin-softmax#2]
你好，按照你的代码运行，我总是遇到下边错误 expected dense_1 to have shape (None, 17187) but got array with shape (17187, 1)。请问该如何处理呀？

**Comment by bojone** [comment]
请详细描述你的使用过程。

**Comment by tzSmilence** [comment]
您好，根据您的代码，我修改了一下两点：1.使用自己的数据，数据格式是按照您发出来的格式要求保存；2.修改了num_train大小。然后就报上述错误不能运行成功

**Comment by bojone** [comment]
@mo-lian 我测了一下，应该是keras版本不够的问题。至少在keras 2.1.0下是不行的，而我的实验环境是2.1.5

**Comment by tzSmilence** [comment]
嗯嗯，多谢苏老师！

**Comment by chenjun0210** [comment]
请问一下，你们对应的tensorflow版本是多少啊？
