### ISSUE TITLE
随epoch增加，loss减小，但是top1、top5、top10效果变差

### ISSUE THREAD

**Issue by zero654655902** [bojone/margin-softmax#8]
你好， 在用您的代码做文本相似度的实验过程中， 发现随着epoch的增加，loss确实是越来越小了， 但是验证集上top1、top5、top10越来越差，比如第一个epoch top1=0.12， 第二个epoch  top1 = 1.0, 随着epoch增加，top1会有震荡，然后就越来越低了，到0.45左右，中间还会有跳变。
并且在新的测试集上验证模型效果，效果不稳定。
训练数据有3千多条，总共是243个类别，epoch_size 是20， embedding_size = 100,
找了很久找不到原因，希望您能帮忙看看，谢谢

**Comment by yaleimeng** [comment]
是不是数量太少，或者数据自身的原因？
我使用近4万组同义句，其中3万做训练集。训练过程正常啊
loss一直下降，验证的top1、top5、top10一直在提升。10个epoch之后top1就上0.9了。

**Comment by bojone** [comment]
@yaleimeng 感谢回复。已经跟@zero654655902 私下分析过了。

**Comment by will-wiki** [comment]
你好，我也出现了这样的情况。是因为我数据集比较少么，目前只有近200组的数据。top的精度随着epoch先是升高，然后再慢慢下降这样
