### ISSUE TITLE
完成训练后，怎样加载模型对更多句子进行预测？

### ISSUE THREAD

**Issue by yaleimeng** [bojone/margin-softmax#9]
训练正常结束了。默认保存了一个sent_sim_amsoftmax.model文件。但不知道怎样在另一个脚本中读取模型（这里只用了某层的中间状态），对新接收的问题，找出几个相似问句。能否给一个demo参考？
另外要预测的新句子只要跟训练集或者验证集内group中某一句相似都可以，对吗？

**Comment by bojone** [comment]
验证集的evaluate()就已经是一个完整的、对应于生产环境的调用例子了呀，请好好读evaluate()的代码。还有最后的most_similar函数。

**Comment by yaleimeng** [comment]
当前的训练代码跟预测代码混在一起，弄了几天还是没搞定，改来改去报错很多难以解决。
能否将读取已保存模型，对新的问题在验证集中做计算/排序的部分独立写个py文件放进来学习一下？
多谢了。 @bojone
